# Generated by Django 5.2.1 on 2025-06-17 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
                ('enrollment_number', models.CharField(blank=True, help_text='رقم تسجيل الطالب الفريد في المدرسة. يتم إنشاؤه تلقائياً.', max_length=50, null=True, unique=True, verbose_name='رقم التسجيل')),
                ('father_name', models.CharField(max_length=255, verbose_name='اسم الأب')),
                ('gender', models.CharField(choices=[('Male', 'ذكر'), ('Female', 'أنثى'), ('Other', 'أخرى')], max_length=10, verbose_name='النوع')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('parent_phone', models.CharField(help_text='رقم هاتف الأب أو الأم للتواصل.', max_length=20, verbose_name='رقم هاتف ولي الأمر')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.section', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'الطالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['enrollment_number'],
            },
        ),
    ]
