# Generated by Django 5.2 on 2025-06-23 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_options_alter_class_unique_together_and_more'),
        ('students', '0003_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_class',
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_class', to='classes.class', verbose_name='المرحلة الدراسية'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('New', 'جديد'), ('Existing', 'قديم')], default='New', max_length=10, verbose_name='حالة الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('Accepted', 'مقبول'), ('Rejected', 'مرفوض'), ('Enrolled', 'مسجل فعال')], default='New', max_length=50, verbose_name='حالة الطالب'),
        ),
    ]
