# Generated by Django 5.2 on 2025-06-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_current_class_student_student_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('Accepted', 'مقبول'), ('Rejected', 'مرفوض'), ('Enrolled', 'مسجل فعال')], default='pending', max_length=50, verbose_name='حالة الطالب'),
        ),
    ]
