# Generated by Django 5.2 on 2025-06-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='status',
            new_name='register_status',
        ),
    ]
