# Generated by Django 5.2 on 2025-06-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_status_student_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='register_status',
            field=models.CharField(choices=[('pending', 'معلق'), ('Accepted', 'مقبول'), ('Rejected', 'مرفوض')], default='pending', max_length=50, verbose_name='حالة الطالب'),
        ),
    ]
