# Generated by Django 5.2.1 on 2025-06-17 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('title', models.CharField(help_text='عنوان وصفي للمحتوى (مثال: محاضرة 1، روابط مفيدة، ملخص الفصل الأول).', max_length=255, verbose_name='عنوان المحتوى')),
                ('content_type', models.CharField(choices=[('text', 'نص'), ('link', 'رابط'), ('file', 'ملف رئيسي')], help_text='اختر نوع المحتوى الأساسي: نص، رابط، أو ملف رئيسي.', max_length=10, verbose_name='نوع المحتوى الأساسي')),
                ('text_content', models.TextField(blank=True, help_text="اكتب المحتوى النصي إذا كان نوع المحتوى الأساسي 'نص'.", null=True, verbose_name='المحتوى النصي')),
                ('link_url', models.URLField(blank=True, help_text="أدخل رابط URL إذا كان نوع المحتوى الأساسي 'رابط'.", max_length=500, null=True, verbose_name='رابط URL')),
                ('main_file', models.FileField(blank=True, help_text="رفع ملف رئيسي (مثل PDF) إذا كان نوع المحتوى الأساسي 'ملف'.", null=True, upload_to='subject_content_main_files/', verbose_name='الملف الرئيسي')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='subject_content_images/', verbose_name='صورة إضافية 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='subject_content_images/', verbose_name='صورة إضافية 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='subject_content_images/', verbose_name='صورة إضافية 3')),
                ('document1', models.FileField(blank=True, null=True, upload_to='subject_content_documents/', verbose_name='مستند إضافي 1')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='subject.subject', verbose_name='المادة الدراسية')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_content', to='teachers.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'محتوى المادة',
                'verbose_name_plural': 'محتويات المواد',
                'ordering': ['subject', 'title'],
            },
        ),
    ]
