# Generated by Django 5.2 on 2025-06-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name': 'الفصل الدراسي', 'verbose_name_plural': 'الفصول الدراسية'},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name',)},
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الفصل'),
        ),
        migrations.AlterField(
            model_name='section',
            name='stream_type',
            field=models.CharField(blank=True, choices=[('General', 'عام'), ('Scientific', 'علمي'), ('Literary', 'أدبي')], default='General', help_text='مثل: علمي، أدبي، عام.', max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='class',
            name='academic_year',
        ),
    ]
