# Generated by Django 5.2 on 2025-06-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user_permissions',
        ),
    ]
