# Generated by Django 5.2.1 on 2025-06-17 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'المعلم',
                'verbose_name_plural': 'المعلمون',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('day_of_week', models.IntegerField(choices=[(1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس'), (5, 'الجمعة'), (6, 'السبت'), (7, 'الأحد')], help_text='اليوم من الأسبوع الذي يكون فيه المعلم متاحًا بشكل عام.', verbose_name='يوم الأسبوع')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='teachers.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'توفر المعلم',
                'verbose_name_plural': 'توفر المعلمين',
                'ordering': ['teacher__user__first_name', 'day_of_week'],
                'unique_together': {('teacher', 'day_of_week')},
            },
        ),
    ]
