# Generated by Django 5.2.1 on 2025-06-17 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('name', models.CharField(help_text='مثال: 2024-2025', max_length=50, unique=True, verbose_name='اسم العام الدراسي')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('is_current', models.BooleanField(default=False, help_text='يجب أن يكون عام دراسي واحد فقط هو الحالي في أي وقت.', verbose_name='هل هو العام الحالي؟')),
            ],
            options={
                'verbose_name': 'عام دراسي',
                'verbose_name_plural': 'سنوات دراسية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('name', models.CharField(help_text='مثال: الفصل الأول، الفصل الثاني، الفصل الصيفي', max_length=100, verbose_name='اسم الفصل الدراسي')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('is_current', models.BooleanField(default=False, help_text='يجب أن يكون فصل دراسي واحد فقط هو الحالي لكل عام دراسي محدد.', verbose_name='هل هو الفصل الحالي؟')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_terms', to='academic.academicyear', verbose_name='العام الدراسي')),
            ],
            options={
                'verbose_name': 'فصل دراسي',
                'verbose_name_plural': 'فصول دراسية',
                'ordering': ['-academic_year__start_date', 'start_date'],
                'unique_together': {('academic_year', 'name')},
            },
        ),
    ]
