# Generated by Django 5.2 on 2025-06-22 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_terms', to='academic.academicyear'),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='هل هو الفصل الحالي؟'),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='هل هو العام الحالي؟'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='اسم العام الدراسي'),
        ),
    ]
