# Generated by Django 5.2 on 2025-06-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_academicterm_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.IntegerField(help_text='1=الأحد, 2=الاثنين, ..., 7=السبت', primary_key=True, serialize=False)),
                ('name_ar', models.CharField(help_text='اسم اليوم  (مثال: الأحد)', max_length=20, unique=True)),
                ('is_school_day', models.BooleanField(default=True, help_text='هل هذا اليوم يوم دراسي عادي؟ (للسماح بالعطلات)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'يوم الأسبوع',
                'verbose_name_plural': 'أيام الأسبوع',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField(help_text='الترتيب التسلسلي للحصة/الفترة في اليوم (مثال: 1, 2, 3...)', unique=True)),
                ('start_time', models.TimeField(help_text='وقت بدء الفترة الزمنية (مثال: 08:00)')),
                ('end_time', models.TimeField(help_text='وقت انتهاء الفترة الزمنية (مثال: 08:45)')),
                ('is_break', models.BooleanField(default=False, help_text='هل هذه الفترة استراحة وليست حصة دراسية؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'الفترة الزمنية للحصة',
                'verbose_name_plural': 'الفترات الزمنية للحصص',
                'ordering': ['slot_number'],
            },
        ),
    ]
