# Generated by Django 5.2.1 on 2025-06-17 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('title', models.CharField(help_text='عنوان الإعلان أو النشاط.', max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(help_text='وصف تفصيلي للإعلان أو النشاط.', verbose_name='الوصف')),
                ('type', models.CharField(choices=[('announcement', 'إعلان'), ('activity', 'نشاط')], default='announcement', help_text='هل هو إعلان عام أم نشاط محدد؟', max_length=20, verbose_name='النوع')),
                ('target_audience', models.CharField(choices=[('all', 'الجميع'), ('teachers', 'المعلمون'), ('students', 'الطلاب'), ('class', 'فصل دراسي'), ('section', 'قسم'), ('subject', 'مادة دراسية')], default='all', help_text='لمن يستهدف هذا الإعلان/النشاط؟', max_length=20, verbose_name='الجمهور المستهدف')),
                ('activity_date', models.DateField(blank=True, help_text="تاريخ حدوث النشاط (يُستخدم إذا كان النوع 'نشاط').", null=True, verbose_name='تاريخ النشاط')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_news_activities', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('target_class', models.ForeignKey(blank=True, help_text="يُحدد إذا كان الجمهور المستهدف 'فصل دراسي'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.class', verbose_name='الفصل المستهدف')),
                ('target_section', models.ForeignKey(blank=True, help_text="يُحدد إذا كان الجمهور المستهدف 'قسم'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.section', verbose_name='القسم المستهدف')),
                ('target_subject', models.ForeignKey(blank=True, help_text="يُحدد إذا كان الجمهور المستهدف 'مادة دراسية'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.subject', verbose_name='المادة المستهدفة')),
            ],
            options={
                'verbose_name': 'إعلان/نشاط',
                'verbose_name_plural': 'الإعلانات والأنشطة',
                'ordering': ['-created_at'],
            },
        ),
    ]
