# Generated by Django 5.2.1 on 2025-06-17 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='مثال: فترة التسجيل للطلاب الجدد 2025', max_length=255, verbose_name='اسم فترة التسجيل')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية فترة التسجيل')),
                ('end_date', models.DateField(verbose_name='تاريخ نهاية فترة التسجيل')),
                ('is_active', models.BooleanField(default=False, help_text='هل هذه الفترة نشطة حالياً؟', verbose_name='نشطة حالياً؟')),
                ('registration_type', models.CharField(choices=[('new_students', 'طلاب جدد'), ('returning_students', 'طلاب عائدون'), ('all', 'الكل')], help_text='لتحديد نوع التسجيل (طلاب جدد/عائدون/الكل)', max_length=20, verbose_name='نوع التسجيل')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_periods', to='academic.academicyear', verbose_name='العام الأكاديمي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registration_periods', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'فترة تسجيل',
                'verbose_name_plural': 'فترات التسجيل',
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
    ]
