# Generated by Django 5.2.1 on 2025-06-17 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('stream_type', models.CharField(blank=True, choices=[('Scientific', 'علمي'), ('Literary', 'أدبي'), ('General', 'عام')], help_text='نوع المسار إذا كانت المادة خاصة بمسار معين (علمي/أدبي).', max_length=50, null=True, verbose_name='نوع المسار')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المادة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف التفصيلي للمادة')),
                ('is_active', models.BooleanField(default=True, help_text='يشير إلى ما إذا كانت هذه المادة متاحة للتدريس.', verbose_name='هل المادة نشطة؟')),
                ('pdf_url', models.URLField(blank=True, help_text='رابط للمنهج الدراسي أو مواد مساعدة بصيغة PDF.', max_length=500, null=True, verbose_name='رابط ملف الـ PDF')),
                ('weekly_sessions', models.IntegerField(help_text='عدد الحصص المخصصة لهذه المادة أسبوعياً.', verbose_name='عدد الحصص الأسبوعية')),
                ('class_obj', models.ForeignKey(blank=True, help_text='الفصل الدراسي الذي تنتمي إليه هذه المادة (مثال: الصف الأول).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_in_class', to='classes.class', verbose_name='الفصل الدراسي المرتبط')),
                ('section', models.ForeignKey(blank=True, help_text='القسم الذي تنتمي إليه هذه المادة (مثال: القسم أ).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_in_section', to='classes.section', verbose_name='القسم المرتبط')),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'المواد الدراسية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('weekly_hours', models.PositiveIntegerField(help_text='عدد الساعات الأسبوعية التي يدرسها المعلم لهذه المادة.', verbose_name='الساعات الأسبوعية')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_by_teachers', to='subject.subject', verbose_name='المادة الدراسية')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_subjects', to='teachers.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'مادة المعلم',
                'verbose_name_plural': 'مواد المعلمين',
                'unique_together': {('teacher', 'subject')},
            },
        ),
    ]
