# Generated by Django 5.2 on 2025-06-27 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_options_alter_class_unique_together_and_more'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSubjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_lessons_required', models.IntegerField(help_text='عدد الحصص الأسبوعية المطلوبة لهذه المادة في هذه الشعبة', verbose_name='عدد الحصص الأسبوعية المطلوبة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_requirements', to='classes.section', verbose_name='الشعبة')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_requirements', to='subject.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'متطلب حصص الشعبة',
                'verbose_name_plural': 'متطلبات حصص الشعب',
                'unique_together': {('section', 'subject')},
            },
        ),
    ]
