# Generated by Django 5.2 on 2025-06-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_sectionsubjectrequirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionsubjectrequirement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='weekly_sessions',
        ),
    ]
